[package]
name = "csv_index"
version = "0.1.0"
authors = ["Otto <otto@ot-to.nl>"]
edition = "2018"

[dependencies]
csv = "1.0.5"
bincode = "1.1.2"

[dependencies.clap]
version = "2.32"
default-features = false
